### PR TITLE
[Master to v0_11] Authenticator SPI

### PR DESCRIPTION
**Pull request by komamitsu**
Cherry-pick https://github.com/treasure-data/digdag/commit/3cf6d7d26d5c9e7be5b6fa4bad473f04034479da (pull request #1324 from treasure-data/master-v10-auth-spi)

### CODE REVIEW

**Comment by komamitsu** [comment]
PTAL @yoyama @szyn @serihiro 

I think this change is safe even with v0_11. It modifies `io.digdag.server.ServerModule#bindAuthenticator` and introduces `BasicAuthenticatorFactory`. But `BasicAuthenticatorFactory` just returns `NoAuthenticator` unless the configuration file doesn’t have any basic auth configuration.

**Review by serihiro — CHANGES_REQUESTED** [review]
(Sorry I just wrongly selected `request changes`)

**Review by serihiro — APPROVED** [review]
LGTM

**Review by szyn — APPROVED** [review]
👍

**Comment by komamitsu** [comment]
Thanks!!

**Pull request merged**
