### PR TITLE
Fix #849. Add INITIAL_TASK flag when sub task generated.

### LINKED ISSUE #849: Group retry does not work in call> operator
Group retry does not work when the digdag script called from call> operator.

### Environment
Digdag version: 0.9.27
Mode: local

### Procedure for reproducing
* parent.dig
```
+call_child:
  call>: ./child.dig
```
* child.dig
```
_retry: 2
+run:
  sh>: sleep 3; exit 1
```
* Run
```
$ digdag  run --rerun ./parent.dig
```

* Result
Only executed one time, not retried.
```
2018-08-27 12:16:06 +0900: Digdag v0.9.27
2018-08-27 12:16:07 +0900 [WARN] (main): Reusing the last session time 2018-08-23T00:00:00+00:00.
2018-08-27 12:16:07 +0900 [INFO] (main): Using session /home/.../.digdag/status/20180823T000000+0000.
2018-08-27 12:16:07 +0900 [INFO] (main): Starting a new session project id=1 workflow name=parent session_time=2018-08-23T00:00:00+00:00
2018-08-27 12:16:08 +0900 [INFO] (0017@[0:default]+parent+call_child): call>: ./child.dig
2018-08-27 12:16:09 +0900 [INFO] (0017@[0:default]+parent+call_child^sub+run): sh>: sleep 3; exit 1
2018-08-27 12:16:12 +0900 [ERROR] (0017@[0:default]+parent+call_child^sub+run): Task failed with unexpected error: Command failed with code 1
java.lang.RuntimeException: Command failed with code 1
        at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
        at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
        at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:312)
        at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:694)
        at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:254)
        at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
        at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
        at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
        at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
        at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:676)
        at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-08-27 12:16:12 +0900 [INFO] (0017@[0:default]+parent^failure-alert): type: notify
error:
  * +parent+call_child^sub+run:
    Command failed with code 1 (runtime)

Task state is saved at /home/.../.digdag/status/20180823T000000+0000 directory.
  * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
  * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
```

### Cause of problem
When added tasks to retry, INITIAL_TASK is not set to state_flags, so the tasks are not picked up in DatabaseSessionStoreManager.copyInitialTasksForRetry().
If I added INITIAL_TASK in TaskControl.addGeneratedSubtasks(), it looks like working correctly.
But I don't know the role of INITIAL_TASK, so it may not correct way.

### PR DESCRIPTION
**Pull request by yoyama**
To fix #849 I would like to set INITIAL_TASK flag when add sub task.
When call operator is processed, WorkFlowExecutor.taskSucceeded() add it as sub task. 
But sub task is not set as initial task, it is ignored when retry process happened.
When WorkFlowExecutor.retryGroupingTask() is called, only initial tasks are copied for retry.

### CODE REVIEW

**Comment by muga** [comment]
Thank you for fixing. I'm still not confident that `boolean isInitialTask` param in `addTasks` method is not necessary according to your fix?

**Comment by yoyama** [comment]
@muga Thank you for your comment.
To my understanding, copyInitialTasksForRetry in DatabaseTaskControlStore(private class in DatabaseSessionStoreManager) try to fetch task as follows.
```java
            List<StoredTask> tasks = handle.createQuery(
                    selectTaskDetailsQuery() + " where t.id " + inLargeIdListExpression(recursiveChildrenIdList) +
                    " and " + bitAnd("t.state_flags", Integer.toString(TaskStateFlags.INITIAL_TASK)) + " != 0" + // only initial tasks
                    " order by t.id asc" // to ensure that tasks are sorted in the newest order
                )
                .map(stm)
                .list();
```
It require INITIAL_TASK state to get retry tasks.

BTW I am afraid that adding INITIAL_TASK state to sub task may cause of secondary effect. 
So another way may be better.

**Comment by yoyama** [comment]
I added tests on both call:> and loop:> opeators with _retry.
@muga Could you check it?

**Comment by yoyama** [comment]
All CI passed. So I merge it.

**Pull request merged**
