### PR TITLE
Fix gradle deprecation warning. Use doLast intead of <<.

### LINKED ISSUE #758: Fix gradle "Task.leftShift(Closure) method has been deprecated" warning
```
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_erdkm0el29ihheeaqmsipw6av$_run_closure2.doCall(/path/to/digdag/build.gradle:251)
```

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
This PR fix #758 issue.
Please take a look when you have a time.

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
I close this PR for rerun CI.

**Comment by muga** [comment]
@hiroyuki-sato Thank you for taking. The change looks good to me. Do you have any concerns to merge this into master? Or do you have any remaining tasks for this?

**Comment by hiroyuki-sato** [comment]
@muga Thank you for the reply.
I have no remaining tasks. Please merge if you ok with that.

**Comment by muga** [comment]
Thank you. Looks good. Merging.

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
