### PR TITLE
Bump-up jquery version, to avoid collapse issue in bootstrap

### PR DESCRIPTION
**Pull request by djKooks**
Hello,
While testing the project in local, seems collapse in `navbar` seems not working well, due to following issue.
https://github.com/twbs/bootstrap/issues/30553

Could you check?

### CODE REVIEW

**Comment by szyn** [comment]
Thank you for creating this PR. It seems the CIs are failing due to the following error: `npm ERR! Invalid: lock file's jquery@3.5.0 does not satisfy jquery@3.5.1`. Could you fix the failure? We need to update `package-lock.json`, too.

**Comment by djKooks** [comment]
@szyn sure! Thanks for notice.

**Comment by djKooks** [comment]
@szyn please let me know if there's any other thing to check 🙏

**Review by szyn — APPROVED** [review]
Looks good to me. Thank you for contributing!

**Pull request merged**
