### PR TITLE
Use Application Default Credential if gcp.credential is absent

### PR DESCRIPTION
**Pull request by rhase**
# What this PR changes

Use [Application Default Credential (ADC)](https://cloud.google.com/docs/authentication/production#automatically) if gcp.credential secret is not defined.  
Applied to bq, bq_ddl, bq_load, bq_extract and gcs_wait.

# Motivation

It's very convenient to use ADC when you run digdag on gce or gke because you don't have to manage service account credentials by your self (Google will manage them for you).  
You can also test workflow on your machine with your google account by `gcloud auth application-default login`. You don't need service account and gcp.credential secret.

### CODE REVIEW

**Comment by yoyama** [comment]
Thank you for your contribution.
It seems good. But could you create unit test for the class ?

**Comment by rhase** [comment]
@yoyama 
Added tests.
Could you review it?

**Comment by szyn** [comment]
@rhase Thank you for adding test cases. Looks good to me 👍 BTW, could you update the target branch to `master`?  We want to merge into master as for this PR. 
Please let me know if you would like me to do it.

**Comment by rhase** [comment]
I tried to change target branch by "Edit" button of this PR, but that seems to have caused unexpected effect...
I guess I should recreate PR to master branch.

**Comment by rhase** [comment]
recreated as #1585

**Pull request closed without merging**
