### PR TITLE
[doc] Add doc about scheduler syntax

### PR DESCRIPTION
**Pull request by tsubaki0102**
This syntax is easy to misleading. Please check it 🙏

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Hello, @tsubaki0102 

Thank you for creating the issue.

Examples may help for users. What do you think to add the table like below?

Now: 2019-02-24 14:18:18 +0900

| schedule               | first session time        | first schedule to run at  |
|------------------------|---------------------------|---------------------------|
| hourly>: "32:32"       | 2019-02-24 14:00:00 +0900 | 2019-02-24 14:32:32 +0900 |
| daily>: "10:32:32"     | 2019-02-25 00:00:00 +0900 | 2019-02-25 10:32:32 +0900 |
| weekly>: "2,10:32:32"  | 2019-02-26 00:00:00 +0900 | 2019-02-24 14:32:32 +0900 |
| monthly>: "2,10:32:32" | 2019-03-02 00:00:00 +0900 | 2019-03-02 10:32:32 +0900 |


And `digdag check` command example also may help. 

```
2019-02-24 14:20:10 +0900: Digdag v0.9.33
  System default timezone: Asia/Tokyo
  ....
  Schedules (1 entries):
    hoge:
      weekly>: "2,10:32:32"
      first session time: 2019-02-26 00:00:00 +0900
      first scheduled to run at: 2019-02-26 10:32:32 +0900 (in 44h 12m 20s)
```

**Comment by tsubaki0102** [comment]
@hiroyuki-sato Thanks for your comment!

> Examples may help for users. What do you think to add the table like below?

It's great idea.  
I added example in 1ad1ed6 . How do you feel about this change?

**Comment by hiroyuki-sato** [comment]
@tsubaki0102 Thank you! 👍 LGTM
@muga @yoyama Please take a look when you have time.

**Comment by yoyama** [comment]
@tsubaki0102 @hiroyuki-sato  Thank you for your contribution. I think it is helpful information!
It is basically good. But I would like to propose a little modification.

1. L64-L76 is equivalent to L35-46. I guess remove L64-L76 may be better.
1. L78-L81 is explanation about cron setting. It is far from the table of syntax. How about move to L34?

**Comment by tsubaki0102** [comment]
@yoyama Thanks for your comment!  :satisfied:

You are quite right. I fixed them in 17f091b . Please confirm.

**Pull request merged**
