### PR TITLE
[will be closed] Add simple test with _export docker in digdag-tests

### PR DESCRIPTION
**Pull request by muga**
follow-up of https://github.com/treasure-data/digdag/pull/1025

### CODE REVIEW

**Comment by muga** [comment]
CI job failed by the following assertion error.
```
acceptance.ShIT > runOnDockerCommandExecutor STANDARD_OUT
    2019-04-08 06:47:22 +0000 [INFO] (Test worker) io.digdag.cli.Arguments: Setting project path to /tmp/junit9095642530339830131
    2019-04-08 06:47:22 +0000 [WARN] (Test worker) io.digdag.cli.Run: Using a new session time 2019-04-08T00:00:00+00:00.
    2019-04-08 06:47:22 +0000 [INFO] (Test worker) io.digdag.cli.Run: Using session /tmp/junit9095642530339830131/.digdag/status/20190408T000000+0000.
    2019-04-08 06:47:22 +0000 [INFO] (Test worker) io.digdag.core.workflow.WorkflowExecutor: Starting a new session project id=1 workflow name=sh_docker session_time=2019-04-08T00:00:00+00:00
    2019-04-08 06:47:24 +0000 [INFO] (0035@[0:default]+sh_docker+docker_run) io.digdag.core.agent.OperatorManager: sh>: echo "test sh operator by _export.docker"
    docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
    See 'docker run --help'.
    2019-04-08 06:47:24 +0000 [ERROR] (0035@[0:default]+sh_docker+docker_run) io.digdag.core.agent.OperatorManager: Task failed with unexpected error: Command failed with code 125
    java.lang.RuntimeException: Command failed with code 125
    	at io.digdag.standards.operator.ShOperatorFactory$ShOperator.runTask(ShOperatorFactory.java:143)
    	at io.digdag.util.BaseOperator.run(BaseOperator.java:35)
    	at io.digdag.core.agent.OperatorManager.callExecutor(OperatorManager.java:315)
    	at io.digdag.cli.Run$OperatorManagerWithSkip.callExecutor(Run.java:705)
    	at io.digdag.core.agent.OperatorManager.runWithWorkspace(OperatorManager.java:257)
    	at io.digdag.core.agent.OperatorManager.lambda$runWithHeartbeat$2(OperatorManager.java:137)
    	at io.digdag.core.agent.LocalWorkspaceManager.withExtractedArchive(LocalWorkspaceManager.java:25)
    	at io.digdag.core.agent.OperatorManager.runWithHeartbeat(OperatorManager.java:135)
    	at io.digdag.core.agent.OperatorManager.run(OperatorManager.java:119)
    	at io.digdag.cli.Run$OperatorManagerWithSkip.run(Run.java:687)
    	at io.digdag.core.agent.MultiThreadAgent.lambda$null$0(MultiThreadAgent.java:127)
    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
    2019-04-08 06:47:26 +0000 [INFO] (0035@[0:default]+sh_docker^failure-alert) io.digdag.core.agent.OperatorManager: type: notify

acceptance.ShIT > runOnDockerCommandExecutor FAILED
    java.lang.AssertionError: 2019-04-08 06:47:22 +0000: Digdag v0.9.36-SNAPSHOT
    error: 
      * +sh_docker+docker_run:
        Command failed with code 125 (runtime)
    Task state is saved at /tmp/junit9095642530339830131/.digdag/status/20190408T000000+0000 directory.
      * Use --session <daily | hourly | "yyyy-MM-dd[ HH:mm:ss]"> to not reuse the last session time.
      * Use --rerun, --start +NAME, or --goal +NAME argument to rerun skipped tasks.
    Expected: is <0>
         but: was <1>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at acceptance.ShIT.runOnDockerCommandExecutor(ShIT.java:93)
```

**Comment by muga** [comment]
need to clean up

**Comment by sonots** [comment]
well, travis is failing

**Comment by muga** [comment]
yea.. sorry I overlooked this failure. take a look

**Comment by muga** [comment]
my comment is invalid in the file. @sonots now ready to use. please let me know if you have any questions.

**Comment by sonots** [comment]
thanks, https://github.com/treasure-data/digdag/pulls is now ready to be merged.

**Comment by sonots** [comment]
thanks, https://github.com/treasure-data/digdag/pull/1025 is now ready to be merged.

**Comment by muga** [comment]
Thanks. ok, let me take a look #1025.

**Pull request closed without merging**
