### PR TITLE
Upgrade Guice to 4.2.x

### PR DESCRIPTION
**Pull request by frsyuki**
Guice 4.0 doesn't work with Java 10. Support to Java 9 and later was
added since Guice 4.2. Changes:

* https://github.com/google/guice/wiki/Guice41
* https://github.com/google/guice/wiki/Guice42

### CODE REVIEW

**Comment by muga** [comment]
`git rebase master` before merging and testing.

**Comment by yoyama** [comment]
@muga I would like to resume this PR.

**Comment by yoyama** [comment]
I will rebase the branch-42 via master.

**Comment by yoyama** [comment]
@muga We need to resolve the following dependency error on guava.

```
Rule 0: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.google.guava:guava:19.0 paths to dependency are:
+-io.digdag:digdag-spi:0.9.38-SNAPSHOT
  +-io.digdag:digdag-client:0.9.38-SNAPSHOT
    +-com.google.guava:guava:19.0
and
+-io.digdag:digdag-spi:0.9.38-SNAPSHOT
  +-io.digdag:digdag-client:0.9.38-SNAPSHOT
    +-com.fasterxml.jackson.datatype:jackson-datatype-guava:2.9.9
      +-com.google.guava:guava:18.0
and
+-io.digdag:digdag-spi:0.9.38-SNAPSHOT
  +-com.google.inject.extensions:guice-multibindings:4.2.2
    +-com.google.inject:guice:4.2.2
      +-com.google.guava:guava:25.1-android
```

**Comment by yoyama** [comment]
I upgrade guava in td-client to guava:25.1-jre as trial.

**Comment by yoyama** [comment]
Next challenge is as follows.

```
+-io.digdag:digdag-client:0.9.38-SNAPSHOT
  +-com.github.rholder:guava-retrying:2.0.0
    +-com.google.code.findbugs:jsr305:2.0.2
and
+-io.digdag:digdag-client:0.9.38-SNAPSHOT
  +-com.google.guava:guava:25.1-jre
    +-com.google.code.findbugs:jsr305:3.0.2
```

**Comment by yoyama** [comment]
As upgrade of guava, littleproxy failed with NoSuchMethodError.
```
acceptance.HttpCallIT > testUserProxy STANDARD_OUT
...
    2019-07-10 17:21:33 +0900 [INFO] (0157@[0:default]+http_call+http_call) io.digdag.core.agent.OperatorManager: http_call>: http://localhost:58401/test
    2019-07-10 17:21:33 +0900 [INFO] (0157@[0:default]+http_call+http_call) io.digdag.standards.operator.HttpOperatorFactory$HttpOperator: Sending HTTP request: GET http://localhost:58401/test
    2019-07-10 17:21:33 +0900 [INFO] (LittleProxy-0-ClientToProxyWorker-0) utils.TestUtils$4$1: Passing request: GET http://localhost:58401/test
    2019-07-10 17:21:33 +0900 [ERROR] (LittleProxy-0-ClientToProxyWorker-0) org.littleshoot.proxy.impl.ClientToProxyConnection: (AWAITING_INITIAL) [id: 0xe7a819b4, L:/127.0.0.1:58403 - R:/127.0.0.1:58404]: Caught an exception on ClientToProxyConnection
    java.lang.NoSuchMethodError: com.google.common.net.HostAndPort.getHostText()Ljava/lang/String;
        at org.littleshoot.proxy.impl.ProxyToServerConnection.addressFor(ProxyToServerConnection.java:961)
        at org.littleshoot.proxy.impl.ProxyToServerConnection.setupConnectionParameters(ProxyToServerConnection.java:832)
        at org.littleshoot.proxy.impl.ProxyToServerConnection.<init>(ProxyToServerConnection.java:199)
...

```

**Comment by yoyama** [comment]
@frsyuki @muga I finally succeeded to pass the CIs.

Could you confirm ?

Overview of current changes are as follows:

- Guice 4.2.2
- Guava 27.1-jre
- google-http-client 1.24.1
- findbugs:jsr305 3.0.2
- littleproxy 2.0.0-beta-4 (forked version. the original is not maintained)

**Comment by muga** [comment]
this is great job 👍 thanks!

**Pull request merged**
