### PR TITLE
Make CI tests more robust

### PR DESCRIPTION
**Pull request by komamitsu**

### CODE REVIEW

**Comment by komamitsu** [comment]
Hmm. This test on Circle CI is still failing. I'll look into the test itself later...
```
acceptance.td.BigQueryIT$DdlIT > testDdl FAILED
    java.lang.AssertionError: Timeout after: PT10M
        at org.junit.Assert.fail(Assert.java:88)
        at utils.TestUtils.expect(TestUtils.java:332)
        at acceptance.td.BigQueryIT$DdlIT.testDdl(BigQueryIT.java:413)
Starting process 'Gradle Test Executor 25'. Working directory: /digdag/digdag-tests Command: /usr/lib/jvm/zulu-8-amd64/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.7.7.201606060606.jar_dzvm8q969wrryrqe9mtffnd9v/jacocoagent.jar=destfile=build/jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false -Xms256m -Xmx256m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /root/.gradle/caches/3.4.1/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 25
Successfully started process 'Gradle Test Executor 25
Initialized native services in: /root/.gradle/native
Gradle Test Executor 25 started executing tests.
```

**Comment by komamitsu** [comment]
With a logging https://github.com/treasure-data/digdag/commit/0550e5fd88a9a7da8c1694c5d86f0e1301a25fa4#diff-c0045db97f569c06872d097205e8af4aR684, I found the cause of the BigQueryIt$DdlIT failure.

```
    2017-08-03 17:04:02 +0000 [INFO] (0088@[0:junit3332304894784970736]+query+run) io.digdag.standards.operator.gcp.BqJobRunner: Submitting BigQuery job: td-digdag-test:digdag_s0_p_junit3332304894784970736_w_query_t_2_a_1_fa9d2265-6dfb-4a1f-9514-af82dcbde520^M
    2017-08-03 17:04:02 +0000 [INFO] (LittleProxy-0-ClientToProxyWorker-1) utils.TestUtils: startRequestFailingProxy: failures=2, n=2, key=CONNECT www.googleapis.com:443, requests.keys=[CONNECT www.googleapis.com:443]^M
    2017-08-03 17:04:02 +0000 [INFO] (LittleProxy-0-ClientToProxyWorker-1) utils.TestUtils$4$1: Passing request: CONNECT www.googleapis.com:443^M
    2017-08-03 17:04:03 +0000 [INFO] (LittleProxy-0-ClientToProxyWorker-1) org.littleshoot.proxy.impl.ClientToProxyConnection: (AWAITING_INITIAL {tunneling}) [id: 0x80a890c7, L:/127.0.0.1:45656 - R:/127.0.0.1:59432]: An IOException occurred on ClientToProxyConnection: Connection reset by peer^M
    2017-08-03 17:04:03 +0000 [INFO] (0088@[0:junit3332304894784970736]+query+run) io.digdag.standards.operator.gcp.BqJobRunner: Checking BigQuery job status: td-digdag-test:digdag_s0_p_junit3332304894784970736_w_query_t_2_a_1_fa9d2265-6dfb-4a1f-9514-af82dcbde520^M
    2017-08-03 17:04:03 +0000 [INFO] (LittleProxy-0-ClientToProxyWorker-2) utils.TestUtils: startRequestFailingProxy: failures=2, n=3, key=CONNECT www.googleapis.com:443, requests.keys=[CONNECT www.googleapis.com:443]^M
    2017-08-03 17:04:03 +0000 [INFO] (LittleProxy-0-ClientToProxyWorker-2) utils.TestUtils$4$1: Simulating Optional.of(500 Internal Server Error) for request: CONNECT www.googleapis.com:443^M
    2017-08-03 17:04:03 +0000 [WARN] (0088@[0:junit3332304894784970736]+query+run) io.digdag.standards.operator.state.PollingRetryExecutor: BigQuery job status check failed: td-digdag-test:digdag_s0_p_junit3332304894784970736_w_query_t_2_a_1_fa9d2265-6dfb-4a1f-9514-af82dcbde520: retrying in 1 seconds^M
    java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 500 Internal Server Error"^M
    :
    2017-08-03 17:24:47 +0000 [INFO] (LittleProxy-0-ClientToProxyWorker-6) utils.TestUtils: startRequestFailingProxy: failures=2, n=79, key=CONNECT www.googleapis.com:443, requests.keys=[CONNECT www.googleapis.com:443]^M
```

`io.digdag.standards.operator.gcp.BqJobRunner` seems to send `CONNECT www.googleapis.com:443` frequently. But it makes `DefaultHttpProxyServer` fail always. We need to fix the naive logic of `utils.TestUtils#startRequestFailingProxy`

**Comment by komamitsu** [comment]
@frsyuki Can you review this pull request?

We've observed that `acceptance.ExecutionTimeoutIT$AttemptTimeoutIT` occasionally still fails and this pull request may not fix it. But I think we can address the test failure of `AttemptTimeoutIT` later as another pull request.

**Comment by frsyuki** [comment]
I see. Because BigQuery client sends many requests and `startRequestFailingProxy` was making request too frequently, test case was causing too many retries. Good catch.

**Comment by frsyuki** [comment]
LGTM! Please merge and also check #614.

**Comment by komamitsu** [comment]
Thank you~

**Pull request merged**
