### PR TITLE
Limit number of active attempts

### LINKED ISSUE #293: Limiting number of active workflow attempts per site
There're schedules and REST API (`PUT /api/attempts`) that issue new attempts. `require>` also issues a  new attempt but it should be implemented as an alias of REST API.

### PR DESCRIPTION
**Pull request by frsyuki**
Fixes #293.

### CODE REVIEW

**Comment by danielnorberg** [comment]
I guess we also need the `ScheduleExecutor` to be smart about this limit and not attempt to start more sessions than allowed.

**Comment by frsyuki** [comment]
My current idea is that `ScheduleExecutor` puts execution of a schedule off for several minutes if `WorkflowExecutor` throws AttemptLimitExceededException. Do you mean that `ScheduleExecutor` needs to be even smarter?

**Comment by danielnorberg** [comment]
That sounds good enough 👍

**Comment by frsyuki** [comment]
Rebased from master.
@danielnorberg PTAL

**Comment by danielnorberg** [comment]
👍

**Pull request merged**
