### PR TITLE
Add support for response body compression

### PR DESCRIPTION
**Pull request by frsyuki**
Add support for response body compression …This change lets Undertow compress response body using gzip or deflate
if client sends requests with `Accept-Encoding: gzip` or
`Accept-Encoding: deflate` header.

This change assumes #589.

When client sends `Accept-Encoding: gzip, deflate`, the server uses `gzip` (gzip has higher priority). This is because the client has a bug with deflate. See #590.

### CODE REVIEW

**Comment by yoyama** [comment]
@komamitsu @muga Is there any reason this PR is not merged even though approved same as #589 ?

**Comment by yoyama** [comment]
Just in case, I will postpone to 0.9.41.

**Comment by yoyama** [comment]
As of discussion in person, we will merge to v0_10 after v0_11 has been created.

**Comment by szyn** [comment]
This change assumes #589 as the description. I will merge this PR and close it.

**Pull request merged**
