### PR TITLE
[WIP] Closeable operator

### PR DESCRIPTION
**Pull request by frsyuki**
This is a follow-up of https://github.com/treasure-data/digdag/pull/276#r78507211

### CODE REVIEW

**Comment by danielnorberg** [comment]
In the long run I would like us to consider executing each operator in a container and utilize the container runtime/platform to clean up after each containerized operation execution.

**Comment by frsyuki** [comment]
That is an interesting idea.

**Comment by frsyuki** [comment]
I think local-mode execution is important because digdag should be able to cover use cases where people use their local machine as a develop environment to gradually improve workflow definitions.
For long term, Digdag should make it possible to use local files even on server environment rather than prohibiting them. Cleaning up all generated files is not a desired direction, in my opinion.
But always deleting `<project-dir>/.digdag/tmp` seems ok without calling `Operator.call`.

**Comment by danielnorberg** [comment]
Yeah, and I think using docker containers for all operators could allow use of local files and "persistent workspaces" etc.

**Comment by frsyuki** [comment]
rebased

**Comment by yoyama** [comment]
I guess this PR enable that each operator can override close().
I think LGTM. But we need additional modification because this PR is old and some operators may be added.
So I added [WIP] to the title.

**Comment by yoyama** [comment]
Close because no progress.

**Pull request closed without merging**
