### PR TITLE
Add Cc and Bcc address to mail operator.

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
This PR implement #886.
Add Cc and Bcc address to `mail>` operator.

@muga Can you take a look when you get a chance?
I'll modify a document and write tests if this change policy is good.

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
@muga I got it. It seems that there is no class for testing `mail>` operator.
I'll try to use [SubEthaMail](https://github.com/voodoodyne/subethasmtp) as the first choice.
Please let me know if you have any good idea for testing `mail>` operator.

**Comment by hiroyuki-sato** [comment]
@muga
Can you take a look at this PR when you have a time?

This PR is 
* Add `Cc` and `Bcc` parameters
* Create some tests
  * I used [GreenMail](http://www.icegreen.com/greenmail/) for testing `mail>` operator.(I tried [SubEtha SMTP](https://github.com/voodoodyne/subethasmtp) first. But I didn't how to assert recipients. That's why I used GreenMail.)
  * Checking to send Email with To, Cc, and Bcc
  * Checking mandatory configurations.
* Update documents.


I do not create the following tests yet. Because of those tests less related to new options.
(And also I don't know how to write those tests yet.)
* SMTP Authentication.
* SSL connection.

**Comment by hiroyuki-sato** [comment]
It seems that due to unrelated reason this PR, CI failed.
https://ci.appveyor.com/project/treasure-data/digdag/builds/19756727/job/q7se86f95pwf1544

The last commit just removed unused import statement.

**Comment by muga** [comment]
Let me take a look and the CI failure.

**Comment by hiroyuki-sato** [comment]
Thank you!

**Pull request merged**
