### PR TITLE
Log networkInterfaceId to status object

### PR DESCRIPTION
**Pull request by myui**
Log network interface id for status JSON object. It's mainly for TD internal auditing but can also be used for OSS.

### CODE REVIEW

**Comment by yoyama** [comment]
Could you confirm the failure of test ?

**Comment by myui** [comment]
Test failures are not related to this PR. Rerunning tests.

**Comment by myui** [comment]
@yoyama test passed green.

**Review by yoyama — APPROVED** [review]
👍

**Pull request merged**
