### PR TITLE
Proposal: optional Swagger API

### PR DESCRIPTION
**Pull request by akirakoyasu**
Add CLI option `--enable-swagger` for REST API document

## Test
Console A: Build digdag & run with `--enable-swagger`
```
./gradlew cli
./pkg/digdag-0.9.13-SNAPSHOT.jar server --memory --enable-swagger
```
Console B: Run Swagger-UI
```
docker run -dp 8080:8080 swaggerapi/swagger-ui
```
Browser: Access Swagger-UI
```
http://localhost:8080/?url=http://localhost:65432/api/swagger.json
```

### CODE REVIEW

**Comment by frsyuki** [comment]
why is swagger useful for digdag?

**Comment by akirakoyasu** [comment]
Swagger produces REST API specification. It helps developers to call API directly or to implement Digdag client library with other languages.

**Comment by pdelagrave** [comment]
Having a documented REST API would be extremely useful. For example when using digdag as the workflow engine component of a larger system. Digdag could be easily controlled by other systems through its REST API.

@frsyuki Is it planned to make the API documented with swagger or something else eventually?

**Comment by pdelagrave** [comment]
Any update on this?

**Comment by muga** [comment]
@akirakoyasu @pdelagrave sorry to be late. My browser got the following error during your test scenario. If you would have any idea to solve it, it would be helpful.

screen shot 2018-09-13 at 1 14 07 am

**Comment by benefacto** [comment]
Any update on this? Would be great to see this merged! 
We have a use case where we need a REST client for digdag: Swagger support would allow us to generate a client library from the resulting Swagger specifications instead of writing our own.

**Comment by muga** [comment]
@benefacto Thank you for pinging us. This might be planned to merge. But I didn't have enough time to take a look details. Will update after I will try it and take a look details. Apologize for slow response.

**Comment by muga** [comment]
Merged. Thanks @akirakoyasu @pdelagrave @benefacto!

**Pull request merged**
