### PR TITLE
Sort workflows and projects

### PR DESCRIPTION
**Pull request by katsuyan**
### Overview
Digdag workflows and projects are sorted by workflow id or project id.
But in web console or cli, it's very hard to see.

So, I sort by workflow name and projects name.

And, I check expected impact.

Fixed functions are called from theses. I think it doesn't impact other things.

```
getLatestActiveWorkflowDefinitions -> WorkflowResource.java(GET "/api/workflows")
getProjects -> ProjectResource.java(GET "/api/projects")
getWorkflowDefinitions -> ProjectRecource.java(GET "/api/projects/{id}/workflows")
```

About index, `workflow_definitions` and `projects` tables have these index. And I think `workflow_definitions` and `projects` tables column will not increase so much. So, there is no impact on performance.

```
 workflow_definitions     | CREATE UNIQUE INDEX workflow_definitions_on_revision_id_and_name ON public.workflow_definitions USING btree (revision_id, name)
 projects                 | CREATE UNIQUE INDEX projects_on_site_id_and_name ON public.projects USING btree (site_id, name)
```

### The result of the correction is here.
- `/`

Digdag

↓

Digdag-4

- `/projects`

Digdag-2

↓

Digdag-5

- `/projects/1`

Digdag-3

↓

Digdag-6

- cli
```
$ java -jar pkg/digdag-0.9.38-SNAPSHOT.jar workflows
2019-06-21 21:51:27 +0900: Digdag v0.9.36
  aaa
    def
    abc
    bcd
  ccc
    def
    abc
    bcd
  bbb
    def
    abc
    bcd

Use `digdag workflows <project-name> <name>` to show details.

```

↓

```
$ java -jar pkg/digdag-0.9.38-SNAPSHOT.jar workflows
2019-06-21 21:48:39 +0900: Digdag v0.9.36
  aaa
    abc
    bcd
    def
  bbb
    abc
    bcd
    def
  ccc
    abc
    bcd
    def

Use `digdag workflows <project-name> <name>` to show details.

```

### The reproduction procedure is here
```
$ ls
abc.dig bcd.dig def.dig

$ java -jar ~/src/github.com/katsuyan/digdag/pkg/digdag-0.9.38-SNAPSHOT.jar push aaa
2019-06-21 21:34:21 +0900: Digdag v0.9.38-SNAPSHOT
Creating .digdag/tmp/archive-4728853173767840533.tar.gz...
  Archiving def.dig
  Archiving abc.dig
  Archiving bcd.dig
Workflows:
  def.dig
  abc.dig
  bcd.dig
Uploaded:
  id: 1
  name: aaa
  revision: a0514723-17a1-4708-9902-0955653d6fc9
  archive type: db
  project created at: 2019-06-21T12:34:23Z
  revision updated at: 2019-06-21T12:34:23Z

Use `digdag workflows` to show all workflows.

$ java -jar ~/src/github.com/katsuyan/digdag/pkg/digdag-0.9.38-SNAPSHOT.jar push ccc
2019-06-21 21:34:25 +0900: Digdag v0.9.38-SNAPSHOT
Creating .digdag/tmp/archive-3055637018388013950.tar.gz...
  Archiving def.dig
  Archiving abc.dig
  Archiving bcd.dig
Workflows:
  def.dig
  abc.dig
  bcd.dig
Uploaded:
  id: 2
  name: ccc
  revision: 92604ca9-6f70-455c-9543-17e9826e2f26
  archive type: db
  project created at: 2019-06-21T12:34:27Z
  revision updated at: 2019-06-21T12:34:27Z

Use `digdag workflows` to show all workflows.

$ java -jar ~/src/github.com/katsuyan/digdag/pkg/digdag-0.9.38-SNAPSHOT.jar push ddd
2019-06-21 21:34:30 +0900: Digdag v0.9.38-SNAPSHOT
Creating .digdag/tmp/archive-5831196262785445958.tar.gz...
  Archiving def.dig
  Archiving abc.dig
  Archiving bcd.dig
Workflows:
  def.dig
  abc.dig
  bcd.dig
Uploaded:
  id: 3
  name: ddd
  revision: 570b31da-3696-43e3-8ba9-3909fd5708c5
  archive type: db
  project created at: 2019-06-21T12:34:31Z
  revision updated at: 2019-06-21T12:34:31Z

Use `digdag workflows` to show all workflows.
```

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
Hello, @katsuyan 

This is just _personal_ opinion.
Thank you for creating this PR.
This setting is using for around three years.
I'm worrying that changing default sort key make confuse users.
How about merging v10 branch if this change is a good improvement?
If a user can choice sort key, it would be more better.

@muga, @yoyama What do you think?

**Comment by yoyama** [comment]
@katsuyan Thanks for your contribution.
As @hiroyuki-sato pointed out, we don't want to database API behavior. (also in v0_10)
There is a possibility to affect digdag-server's processing seriously.

**Comment by katsuyan** [comment]
Thank you for your comments.
I understand that you don't want to change database API behavior.
But, not sorted workflows are hard to see.

So, I try to consider another way.

**Comment by hiroyuki-sato** [comment]
Hello, @katsuyan 

I think It would be a good extension if API set sort key as option.
(I think this is my opinion too). It doesn't change default behavior.

Best regards.

```
GET "/api/projects?sort=name"
```

**Comment by katsuyan** [comment]
I'm sorry to reply late, I try to above method.

**Comment by yoyama** [comment]
Close because no activity.

**Pull request closed without merging**
