### PR TITLE
digdag-ui: reduced flow errors

### PR DESCRIPTION
**Pull request by seiyab**
`npm run flow` found 32 errors.
I resolved 17 of them.

I also have some questions related this PR.

- What do you think about flowtype?
    - These errors seem to be left for a long time.
    - Type errors are not checked in CI.
- Can I update `flow-bin`?
    - VSCode plugin doesn't work because installed `flow-bin` is extremely old
      Screen Shot 2021-09-12 at 20 57 48
    - On the other hand, newer `flow-bin` will find **more than 100 errors** in this project.
- Do you have any plan to change over to TypeScript?
    - [Flow seems to prioritize Facebook internal usage](https://medium.com/flow-type/clarity-on-flows-direction-and-open-source-engagement-e721a4eb4d8b).

### CODE REVIEW

**Comment by szyn** [comment]
Thank you for creating this PR!

> What do you think about flowtype?

To be honest, it's been around for a long time, and I don't know the background on the use of flowtype, so I couldn't comment from an accurate position.

> Can I update flow-bin?

Feel free to update it, but it will be hard to fix the errors, though.

> Do you have any plan to change over to TypeScript?

My understanding is that there has never been a clear plan to change to TypeScript. In my opinion, migrating to typescript is a better choice than trying hard to upgrade/maintain flow. Let me create an issue for that.

**Comment by seiyab** [comment]
@szyn 
Thank you very much for your honest comment.
> Let me create an issue for that.

Thank you. Describing as an issue makes community to be able to improve it.

**Comment by seiyab** [comment]
I resolved conflict rebasing branch.
Correcting types will also help migration.

**Review by szyn — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
