### PR TITLE
[wip] Bump up resteasy-client to 3.0.23.Final

### PR DESCRIPTION
**Pull request by takanamito**
Bump up resteasy-client which includes this bug fix.
resteasy/Resteasy#1169

This issue is referred to #756

### CODE REVIEW

**Comment by muga** [comment]
a lot of changes are included..
https://github.com/resteasy/Resteasy/compare/3.0.13.Final...3.0.23.Final

**Comment by takanamito** [comment]
@muga However, reported bug is fixed by `3.0.23.Final`.
Should I send some PRs which includes updating resteasy version little by little ?

**Comment by muga** [comment]
@takanamito Thank you for upgrading! It looks good to me. Just it was hard to take a look a lot of changes..

**Comment by takanamito** [comment]
Sorry, I misunderstood. Thank you for approving my commit 😄

**Comment by muga** [comment]
@takanamito Sorry, I will slide this PR from v0.9.25 to v0.9.26. After upgrading resteasy version, Digdag server show the following warning messages in access log. I believe that the warning is not critical but, just in case, I will take a look the cause.

**Comment by muga** [comment]
follow-up PR is https://github.com/treasure-data/digdag/pull/779

**Comment by takanamito** [comment]
Thank you for letting me know.
I wait for fixing it.

**Pull request merged**
