### PR TITLE
Fix examples to work

### PR DESCRIPTION
**Pull request by sonots-zozo**
Previously, I got errors with:

```
$ cd examples
$ digdag run params.dig --rerun

2019-02-06 19:48:34 +0900 [INFO] (0017@[0:default]+params+simple): py>: examples.params.simple
Traceback (most recent call last):
  File "<stdin>", line 85, in digdag_inspect_command
ImportError: No module named 'examples.params'
```

This PR fixes examples to work.

### CODE REVIEW

**Comment by sonots-zozo** [comment]
Please let me know if there are correct ways to run digdag examples.

**Comment by hiroyuki-sato** [comment]
JFYI 

I roughly checked another `dig` files.
It seems that other workflows also need to move some files into `examples/examples` directory.
https://gist.github.com/hiroyuki-sato/e21d9bcccb56a2a54c739e64b367a789

**Comment by yoyama** [comment]
@sonots Thanks your PR. I agree. I am also thinking current directory structure for examples should be changed. 
@hiroyuki-sato Thanks for detail information. It is very helpful!

**Comment by sonots-zozo** [comment]
| Workflow    | results | notes         |
|-------------------|----|---------------|
| basic             | OK |               |
| call              | OK |               |
| check_task        | FIXED | |
| conditions        | FIXED | |
| emr               | -  | No environment |
| error_task        | FIXED | |
| export_params     |  FIXED  | |
| generate_subtasks |  NG  | |
| http_for_each     | OK |               |
| include           | FIXED | |
| js_vars           | OK |               |
| mail              | - |  No environment |
| params            | FIXED | |
| python_args       | FIXED ||
| ruby_args         | FXIED | |
| schedule_daily    | - | Scheduler is not verified |
| schedule_hourly   | - | Scheduler is not verified |
| schedule_weekly   | - | Scheduler is not verified |
| shell_envvar      | FIXED | |
| sla               | - | |
| sla_duration      | - | |
| td_for_each       | -  | No environment |
| treasuredata      | -  | No environment |

**Comment by sonots-zozo** [comment]
I moved scripts to `tasks` directory as https://docs.digdag.io/python_api.html documents usually use the directory.

**Comment by sonots-zozo** [comment]
It looks `generate_subtasks` does not work with python3.

```
2019-02-06 21:47:17 +0900 [INFO] (0017@[0:default]+generate_subtasks+parallel_process): py>: tasks.generate_subtasks.ParallelProcess.run
2019-02-06 21:47:17 +0900 [INFO] (0020@[0:default]+generate_subtasks+parallel_process^sub+subtask2): py>: tasks.generate_subtasks.subtask
2019-02-06 21:47:17 +0900 [INFO] (0019@[0:default]+generate_subtasks+parallel_process^sub+subtask1): py>: tasks.generate_subtasks.subtask
2019-02-06 21:47:17 +0900 [INFO] (0017@[0:default]+generate_subtasks+parallel_process^sub+subtask0): py>: tasks.generate_subtasks.subtask
Traceback (most recent call last):
  File "<stdin>", line 87, in digdag_inspect_command
AttributeError: 'module' object has no attribute 'subtask'
```

It seems `tasks.generate_subtasks.ParallelProcess.subtask` is correct, not `tasks.generate_subtasks.subtask`. Probably, `digdag-standards/build/resources/main/digdag/standards/py/runner.py` needs to be fixed.

**Comment by sonots** [comment]
`generate_subtasks` should be fixed via https://github.com/treasure-data/digdag/pull/972.

**Comment by yoyama** [comment]
LGTM. Thanks very much.
I will fix merge conflict and a minor issue then will merge this.

**Pull request merged**
