### PR TITLE
[doc] Fix `release' has type `bytes', defaults to `str' WARNING.

### PR DESCRIPTION
**Pull request by hiroyuki-sato**
I'm not familiar Python.
This PR fixes the following error. @szyn Can you take a look when you have time?
Does this issue specifically in my environment?

```
>>> subprocess.check_output(['git', 'describe', '--abbrev=0', '--tags'])[1:].strip()
b'0.9.33'

>>> subprocess.check_output(['git', 'describe', '--abbrev=0', '--tags'])[1:].strip().decode("utf-8")
'0.9.33'
```

## Before fix

```
% make html
LC_ALL=en_US.UTF-8 sphinx-build -b html -d build/doctrees   src build/html
Running Sphinx v1.5.3
WARNING: The config value `release' has type `bytes', defaults to `str'.
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: [config changed] 150 added, 0 changed, 0 removed
reading sources... [100%] workflow_definition
/path/to/digdag/digdag-docs/src/releases.rst:4: WARNING: toctree contains reference to nonexisting document '# add new version here'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /path/to/digdag/digdag/digdag-docs/src/tutorials.rst:: WARNING: document isn't included in any toctree
done
preparing documents...
Exception occurred:
  File "/path/to/.pyenv/versions/3.6.0/lib/python3.6/site-packages/sphinx/builders/html.py", line 335, in prepare_writing
    release = return_codes_re.sub('', self.config.release),
TypeError: cannot use a string pattern on a bytes-like object
The full traceback has been saved in /var/folders/3s/5cm202m95zsglpy26c6_7j9m0000gn/T/sphinx-err-g_4dtfw3.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 
```

## After fix

```
make html
LC_ALL=en_US.UTF-8 sphinx-build -b html -d build/doctrees   src build/html
Running Sphinx v1.5.3
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 150 source files that are out of date
updating environment: 150 added, 0 changed, 0 removed
reading sources... [100%] workflow_definition
/path/to/digdag/digdag-docs/src/releases.rst:4: WARNING: toctree contains reference to nonexisting document '# add new version here'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /path/to/digdag/digdag-docs/src/tutorials.rst:: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] workflow_definition
generating indices... genindex
writing additional pages... search
copying images... [100%] _static/workflow-as-code.png
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

Build finished. The HTML pages are in build/html.
```

### CODE REVIEW

**Comment by hiroyuki-sato** [comment]
It is said that requires Python3 for building a document in README.md
But now CI still use Python2.  That's why this error occurred.

Thank you @szyn

**Comment by yoyama** [comment]
I discussed about it with @muga and we should move CI with Python3.
Please wait for it.

**Comment by muga** [comment]
@szyn @hiroyuki-sato As talked with @yoyama in-person, what do you think that we'd better to create specific Docker image for making document? Currently our Docker image has been used for all purpose, releasing, testing, and documenting.
https://github.com/treasure-data/digdag/blob/master/docker/bootstrap/dependencies.sh#L34

**Comment by szyn** [comment]
@muga Thank you for suggesting. I agree with you. It's a good idea to create a new image for making docs.

**Comment by yoyama** [comment]
@hiroyuki-sato we had already moved to Python3 by #1154 
Could you check it ?

**Comment by hiroyuki-sato** [comment]
@yoyama Thanks!
I already checked Python3.
https://github.com/treasure-data/digdag/pull/1148#issuecomment-501695600
And Now I also checked Spinx 2.2.1 build. LGTM.
Close this issue.

**Pull request closed without merging**
